name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 6'
defaults:
  run:
    shell: bash
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '^3.9'
            os: macos-latest
          - python: 3.8
            os: ubuntu-latest
          - python: 3.6
            os: windows-latest
          - python: 3.6
            os: ubuntu-latest
            versions: minimal
    runs-on: ${{matrix.os}}
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - name: Pin to lowest versions
        if: matrix.versions == 'minimal'
        run: |
          sed -i -E 's/ >=/ ==/' pyproject.toml
          git diff -U1 --color
      - name: Setup virtualenv
        uses: syphar/restore-virtualenv@d0a933d92488e0505e012c3367e3f987a6276f5a
        with:
          requirement_files: pyproject.toml
      - name: Install packages
        run: |
          python -m pip install -U pip'>=19'; pip install -U wheel
          perl -ne '$p=0 if /[\[\]]/; print "$1\0" if $p && /^ *"(.+?)"/; $p=1 if /^(test|lint) =/' pyproject.toml |
            xargs -0 -t pip install -U --upgrade-strategy=eager .
      - name: Test
        run: |
          .tools/ci.sh with_groups
      - name: Check formatting
        if: matrix.versions == null
        run: |
          git diff --exit-code --color
